In [3]:


with open("Sample1.txt","r") as document:
    file = document.readline()
print(file)

Utilitatis causa amicitia est quaesita.

In [4]:
import pandas as pd
files =pd.read_excel('Financial Sample.xlsx')
print(files.head(5))

      Segment  Country    Product Discount Band  Units Sold  \
0  Government   Canada  Carretera           NaN      1618.5
1  Government  Germany  Carretera           NaN      1321.0
2   Midmarket   France  Carretera           NaN      2178.0
3   Midmarket  Germany  Carretera           NaN       888.0
4   Midmarket   Mexico  Carretera           NaN      2470.0

   Manufacturing Price  Sale Price  Gross Sales  Discounts    Sales     COGS  \
0                    3          20      32370.0        0.0  32370.0  16185.0
1                    3          20      26420.0        0.0  26420.0  13210.0
2                    3          15      32670.0        0.0  32670.0  21780.0
3                    3          15      13320.0        0.0  13320.0   8880.0
4                    3          15      37050.0        0.0  37050.0  24700.0

    Profit       Date  Month Number Month Name  Year
0  16185.0 2014-01-01             1    January  2014
1  13210.0 2014-01-01             1    January  2014
2  10890.0 2014-06-01             6       June  2014
3   4440.0 2014-06-01             6       June  2014
4  12350.0 2014-06-01             6       June  2014

In [6]:
files.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [7]:
files.index

RangeIndex(start=0, stop=700, step=1)

In [40]:
files.describe().head(3)

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.000000,700.000000,700.000000,700.000000,700.000000,700.0000,700.000000,700.000000,700,700.0,700.00
mean,1608.294286,96.477143,118.428571,182759.426429,13150.354629,169609.0718,145475.211429,24133.860371,2014-04-28 21:36:00,7.9,2013.75
min,200.000000,3.000000,7.000000,1799.000000,0.000000,1655.0800,918.000000,-40617.500000,2013-09-01 00:00:00,1.0,2013.00

In [8]:
# to find distinct countries
print(set(files['Country']))

{'Mexico', 'France', 'United States of America', 'Canada', 'Germany'}

In [9]:
#data standardization 
files['Country'] = files["Country"].replace('United States of America','USA')

In [42]:
# to select columns

files.groupby('Country')['Sale Price'].sum()

Country
Canada     16580
France     16580
Germany    16580
Mexico     16580
USA        16580
Name: Sale Price, dtype: int64

In [38]:
# which country made the highest profit from sales
print(
    files.groupby('Country')['Profit']
    .sum()
    .round(2)
    .sort_values(ascending =False)
    
)

Country
France     3781020.78
Germany    3680388.82
Canada     3529228.88
USA        2995540.66
Mexico     2907523.11
Name: Profit, dtype: float64

In [44]:
# which country had  more units sold to
files.groupby('Country')['Units Sold'].sum().sort_values(ascending = False)

Country
Canada     247428.5
France     240931.0
USA        232627.5
Mexico     203325.0
Germany    201494.0
Name: Units Sold, dtype: float64

In [76]:
print(set(files['Discount Band']))

{'Low', 'High', 'Medium', nan}

In [75]:
# to find which products and countries have a high discount band--total count of high discount band offered is 245
# which country had High discount band the most?
files[files['Discount Band'] == 'High'].groupby('Country').size().sort_values(ascending =False)

Country
Mexico     56
Canada     53
USA        51
France     45
Germany    40
dtype: int64

In [77]:
# to find which products and countries have a low discount band--total count of high discount band offered is 245
# which country had the least discount band?
files[files['Discount Band'] == 'Low'].groupby('Country').size().sort_values(ascending =False)

Country
Germany    34
USA        34
Canada     31
France     31
Mexico     30
dtype: int64

In [96]:
# which product made the highest profit and how many units sold
files.groupby("Product")[['Profit','Units Sold']].sum().round(2).sort_values(by= 'Profit', ascending = False)

               Profit  Units Sold
Product
Paseo      4797437.95    338239.5
VTT        3034608.02    168783.0
Amarilla   2814104.06    155315.0
Velo       2305992.46    162424.5
Montana    2114754.88    154198.0
Carretera  1826804.88    146846.0

In [101]:
files[files['Product'] == 'Paseo'].groupby('Country').count().sort_values(ascending = False)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'